### ISSUE TITLE
Use LV2 Atom instead of Event extension

### ISSUE THREAD

**Issue by jofemodo** [jeremysalwen/So-synth-LV2#2] opened 2018-10-16 16:45 UTC
As LV2 event extension is deprecated and removed from most of LV2 hosts, the so-synth plugins can't be used never more in modern systems. The MIDI subsystem should be updated for using Atom extension, the new LV2 way of managing events.

You can find a simple implementation example here:

http://lv2plug.in/book/#_midi_gate

And you can read the discussion about this subject here:

http://lists.lv2plug.in/pipermail/devel-lv2plug.in/2014-January/000642.html

Regards,

**Comment by jerash** [comment] 2020-01-04 21:56
hey @jofemodo I was about to ask if we could have those synths on zynthian, so your comment means thatt hey can be compiled on rpi but would not br totally usable because of the incorrect LV2 event management ?

**Comment by jofemodo** [comment] 2020-01-05 01:02
Hi @jerash !

AFAIK, the Event extension is deprecated and has been removed from recent LV2 hosts, including Jalv and mod-host. This repository seems to be unmaintained, so ... if we want to see the so-synth running on zynthian, someone should take a step forward and update the code for getting it to work with atom.

Regards,

**Comment by jeremysalwen** [comment] 2020-01-05 12:23
I have uploaded a new version to the upstream branch which ports to use the atom extension.   I tested it out with jalv, and they are working except 666.  I can see it is receiving the events, but something else must be wrong.  I vaguely remember that there was some issue with the default settings and you needed to do something else to get it to make sound, but not sure.

**Comment by jeremysalwen** [comment] 2020-01-06 02:52
Ah, found the docs, you need the modwheel to get it to make any sounds: http://d00m.org/~someone/so666/  I confirmed it is working.  Will push a new release.

**Comment by jeremysalwen** [comment] 2020-01-06 04:21
Released as version 1.5 (https://github.com/jeremysalwen/So-synth-LV2/releases/tag/upstream%2F1.5) which has the support.  Still working on getting it packaged for debian.

**Closed as completed by jeremysalwen** 2020-01-06 04:21 UTC

**Comment by jerash** [comment] 2020-01-06 07:25
Thanks @jeremysalwen for the quick follow up. I'll try these soon !

**Comment by jofemodo** [comment] 2020-01-08 11:45
Hi @jeremysalwen !

I've tested the new version and it works OK!
It's already integrated in zynthian ;-)

Thanks a lot!

**Comment by jofemodo** [comment] 2020-01-08 13:52
Some possibility of having "ControlMode" value equal to "Control Ports" by default? ;-)
It's a little annoying having to toggle this control every time you add a new plugin instance ...

**Comment by jeremysalwen** [comment] 2020-01-09 07:07
If you send a pull request I'll accept it :)

**Comment by jofemodo** [comment] 2020-01-09 09:37
Sent ;-)
Only for kl5 and 404.
For 666 is more convenient to conserve the current behaviour, as you need the mod-wheel for getting some sound ... unless a LV2 "feedback" control port is added 0;-)
